### ISSUE TITLE
RUN SCRIPT and non-interactive mode incorrectly parses S-T join as S-S and aborts

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1637]
Version: 5.0.0-rc3 (Docker)

Script seems (c.f #1638 - it doesn't actually say) to barf out at the point of join a join between PAGEVIEWS_TRANSFORMED (stream) and USERS_5PART (table). This SQL is valid and runs fine when entered manually in the CLI.

Happens with both `RUN SCRIPT` in CLI, and `--queries-file` in ksql-server

Run from ksql-server: 

	docker run \
	    -v $PWD/examples.sql:/data/examples.sql \
	    --network tutorials_default \
	    -e KSQL_BOOTSTRAP_SERVERS=kafka:39092 \
	    -e KSQL_KSQL_SERVICE_ID=rmoff_test_01 \
	    -e KSQL_KSQL_QUERIES_FILE=/data/examples.sql \
	    -e KSQL_KSQL_SCHEMA_REGISTRY_URL=http://schema-registry:8081 \
	    confluentinc/cp-ksql-server:5.0.0-rc3

Error from ksql-server: 

	[2018-07-26 16:28:23,798] ERROR Failed to start KSQL Server with query file: /data/examples.sql (io.confluent.ksql.rest.server.StandaloneExecutor:70)
	io.confluent.ksql.util.KsqlException: Stream-Stream joins must have a WITHIN clause specified. None was provided. To learn about how to specify a WITHIN clause with a stream-stream join, please visit: https://docs.confluent.io/current/ksql/docs/syntax-reference.html#create-stream-as-select
		at io.confluent.ksql.planner.plan.JoinNode$StreamToStreamJoiner.join(JoinNode.java:356)
		at io.confluent.ksql.planner.plan.JoinNode.buildStream(JoinNode.java:187)
		at io.confluent.ksql.planner.plan.ProjectNode.buildStream(ProjectNode.java:124)
		at io.confluent.ksql.planner.plan.KsqlStructuredDataOutputNode.buildStream(KsqlStructuredDataOutputNode.java:100)
		at io.confluent.ksql.physical.PhysicalPlanBuilder.buildPhysicalPlan(PhysicalPlanBuilder.java:106)
		at io.confluent.ksql.QueryEngine.buildQueryPhysicalPlan(QueryEngine.java:199)
		at io.confluent.ksql.QueryEngine.buildPhysicalPlans(QueryEngine.java:165)
		at io.confluent.ksql.KsqlEngine.planQueries(KsqlEngine.java:228)
		at io.confluent.ksql.KsqlEngine.createQueries(KsqlEngine.java:618)
		at io.confluent.ksql.rest.server.StandaloneExecutor.executeStatements(StandaloneExecutor.java:118)
		at io.confluent.ksql.rest.server.StandaloneExecutor.start(StandaloneExecutor.java:67)
		at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:60)
		at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:46)
	[2018-07-26 16:28:23,814] INFO Server shutting down (io.confluent.ksql.rest.server.KsqlServerMain:64)

Error from CLI: 

	ksql> RUN SCRIPT '/data/examples.sql';
	io.confluent.ksql.util.KsqlException: Stream-Stream joins must have a WITHIN clause specified. None was provided. To learn about how to specify a WITHIN clause with a stream-stream join, please visit: https://docs.confluent.io/current/ksql/docs/syntax-reference.html#create-stream-as-select
	ksql> show streams;

	 Stream Name                      | Kafka Topic                      | Format
	---------------------------------------------------------------------------------
	 PAGEVIEWS_TRANSFORMED            | PAGEVIEWS_TRANSFORMED            | JSON
	 PAGEVIEWS_TRANSFORMED_PRIORITY_1 | PAGEVIEWS_TRANSFORMED_PRIORITY_1 | JSON
	 PAGEVIEWS_TRANSFORMED_PRIORITY_2 | PAGEVIEWS_TRANSFORMED_PRIORITY_2 | JSON
	 PAGEVIEWS                        | pageviews                        | DELIMITED
	---------------------------------------------------------------------------------
	ksql> show tables;

	 Table Name  | Kafka Topic | Format | Windowed
	-----------------------------------------------
	 USERS_5PART | USERS_5PART | JSON   | false
	 USERS       | users       | JSON   | false
	-----------------------------------------------

Source SQL: 

```
    CREATE STREAM pageviews 
      (viewtime BIGINT, 
       userid VARCHAR, 
       pageid VARCHAR) 
      WITH (KAFKA_TOPIC='pageviews', 
            VALUE_FORMAT='DELIMITED');
    CREATE TABLE users 
      (registertime BIGINT, 
       gender VARCHAR, 
       regionid VARCHAR, 
       userid VARCHAR, 
       interests array<VARCHAR>, 
       contactinfo map<VARCHAR, VARCHAR>) 
      WITH (KAFKA_TOPIC='users', 
            VALUE_FORMAT='JSON', 
            KEY = 'userid');
    CREATE STREAM pageviews_transformed 
      WITH (TIMESTAMP='viewtime', 
            PARTITIONS=5, 
            VALUE_FORMAT='JSON') AS 
      SELECT viewtime, 
             userid, 
             pageid, 
             TIMESTAMPTOSTRING(viewtime, 'yyyy-MM-dd HHmmss.SSS') AS timestring 
      FROM pageviews 
      PARTITION BY userid;
    CREATE STREAM pageviews_transformed_priority_1 
      WITH (TIMESTAMP='viewtime', 
            PARTITIONS=5, 
            VALUE_FORMAT='JSON') AS 
      SELECT viewtime, 
             userid, 
             pageid, 
             TIMESTAMPTOSTRING(viewtime, 'yyyy-MM-dd HHmmss.SSS') AS timestring 
      FROM pageviews 
      WHERE userid='User_1' OR userid='User_2' 
      PARTITION BY userid;
    CREATE STREAM pageviews_transformed_priority_2 
          WITH (TIMESTAMP='viewtime', 
                PARTITIONS=5, 
                VALUE_FORMAT='JSON') AS 
      SELECT viewtime, 
             userid, 
             pageid, 
             TIMESTAMPTOSTRING(viewtime, 'yyyy-MM-dd HHmmss.SSS') AS timestring 
      FROM pageviews 
      WHERE userid<>'User_1' AND userid<>'User_2' 
      PARTITION BY userid;
    CREATE TABLE users_5part 
        WITH (PARTITIONS=5) AS 
        SELECT * FROM USERS;
    CREATE STREAM pageviews_enriched AS 
      SELECT pv.viewtime, 
             pv.userid AS userid, 
             pv.pageid, 
             pv.timestring, 
             u.gender, 
             u.regionid, 
             u.interests, 
             u.contactinfo 
      FROM pageviews_transformed pv 
      LEFT JOIN users_5part u ON pv.userid = u.userid;
    CREATE TABLE pageviews_per_region AS 
      SELECT regionid, 
             count(*) 
      FROM pageviews_enriched 
      GROUP BY regionid;
    CREATE TABLE pageviews_per_region_per_minute AS 
      SELECT regionid, 
             count(*) 
      FROM pageviews_enriched 
      WINDOW TUMBLING (SIZE 1 MINUTE) 
      GROUP BY regionid;
   CREATE TABLE pageviews_per_region_per_30secs AS 
      SELECT regionid, 
             count(*) 
      FROM pageviews_enriched 
      WINDOW TUMBLING (SIZE 30 SECONDS) 
      WHERE UCASE(gender)='FEMALE' AND LCASE(regionid)='region_6' 
      GROUP BY regionid;
   CREATE TABLE pageviews_per_region_per_30secs10secs AS 
      SELECT regionid, 
             count(*) 
      FROM pageviews_enriched 
      WINDOW HOPPING (SIZE 30 SECONDS, ADVANCE BY 10 SECONDS) 
      WHERE UCASE(gender)='FEMALE' AND LCASE (regionid) LIKE '%_6' 
      GROUP BY regionid;
   CREATE TABLE pageviews_per_region_per_session AS 
      SELECT regionid, 
             count(*) 
      FROM pageviews_enriched 
      WINDOW SESSION (60 SECONDS) 
      GROUP BY regionid;
    CREATE STREAM pageviews_interest_contact AS 
   SELECT interests[0] AS first_interest, 
             contactinfo['zipcode'] AS zipcode, 
             contactinfo['city'] AS city, 
             viewtime, 
             userid, 
             pageid, 
             timestring, 
             gender, 
             regionid 
      FROM pageviews_enriched;
```

**Comment by apurvam** [comment]
This seems to have the same root cause as https://github.com/confluentinc/ksql/issues/1320 and should be fixed by https://github.com/confluentinc/ksql/pull/1599.

Essentially, the headless mode doesn't do proper type resolution of the entities.

Right @hjafarpour ?

**Comment by apurvam** [comment]
Actually, @rmoff I cannot reproduce with the following queries file:

```
create stream pageviews (viewtime bigint, userid varchar, pageid varchar) WITH (kafka_topic='pageviews', value_format='json');
create table users (userid varchar, reginid varchar, gender varchar) WITH (kafka_topic='users', value_format='json', key='userid');

create stream pageviews_female as select u.userid, p.pageid, u.gender from pageviews p LEFT JOIN users u on p.userid = u.userid;
```

**Comment by apurvam** [comment]
Running the tarball distribution of 5.0.0-rc3 with that queries file, it 'just works'.

**Comment by hjafarpour** [comment]
This is a bug in Application(headless) mode and #1599 will fix it. It still won't work for `run script` and we are thinking of deprecating `run script` and replacing it with a more intuitive and robust way to run a batch of statements.

**Comment by apurvam** [comment]
@rmoff I can verify that your particular script fails on 5.0.0-rc3. It also fails on 4.1.1 with:
```
[2018-07-26 12:56:28,456] ERROR Failed to start KSQL Server with query file: /Users/apurva/workspace/cp-downloads/confluent-5.0.0/robin.sql (io.confluent.ksql.rest.server.StandaloneExecutor:67)
io.confluent.ksql.util.KsqlException: Unsupported Join. Only stream-table joins are supported, but was io.confluent.ksql.planner.plan.StructuredDataSourceNode@420bc288-io.confluent.ksql.planner.plan.StructuredDataSourceNode@df5f5c0
        at io.confluent.ksql.planner.plan.JoinNode.tableForJoin(JoinNode.java:204)
        at io.confluent.ksql.planner.plan.JoinNode.buildStream(JoinNode.java:163)
        at io.confluent.ksql.planner.plan.ProjectNode.buildStream(ProjectNode.java:121)
        at io.confluent.ksql.planner.plan.KsqlStructuredDataOutputNode.buildStream(KsqlStructuredDataOutputNode.java:94)
        at io.confluent.ksql.physical.PhysicalPlanBuilder.buildPhysicalPlan(PhysicalPlanBuilder.java:127)
        at io.confluent.ksql.QueryEngine.buildQueryPhysicalPlan(QueryEngine.java:194)
        at io.confluent.ksql.QueryEngine.buildPhysicalPlans(QueryEngine.java:162)
        at io.confluent.ksql.KsqlEngine.planQueries(KsqlEngine.java:203)
        at io.confluent.ksql.KsqlEngine.createQueries(KsqlEngine.java:592)
        at io.confluent.ksql.rest.server.StandaloneExecutor.executeStatements(StandaloneExecutor.java:124)
        at io.confluent.ksql.rest.server.StandaloneExecutor.start(StandaloneExecutor.java:64)
        at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:41)
```

Basically, KSQL in non-interactive mode assumes everything is a stream when building a logical plan, and then subsequently fails if the types are incorrect when building the physical plan. 

What you can do to workaround this in your script is:
```
 CREATE TABLE users_5part 
        WITH (PARTITIONS=5) AS 
        SELECT * FROM USERS;
 CREATE TABLE users_5part_tmp (
       registertime BIGINT, 
       gender VARCHAR, 
       regionid VARCHAR, 
       userid VARCHAR, 
       interests array<VARCHAR>, 
       contactinfo map<VARCHAR, VARCHAR>) 
    WITH (
       kafka_topic='USERS_5PART', value_format='JSON', key='userid');
 CREATE STREAM pageviews_enriched AS 
      SELECT pv.viewtime, 
             pv.userid AS userid, 
             pv.pageid, 
             pv.timestring, 
             u.gender, 
             u.regionid, 
             u.interests, 
             u.contactinfo 
      FROM pageviews_transformed pv 
      LEFT JOIN users_5part_tmp u ON pv.userid = u.userid;
```

Basically, that introduces a DDL statement to force KSQL in non-interactive mode to assign the entity the right type (ie. table). I tried your script with the addition of the `users_5part_tmp` table above, and it works.

Hojjat's PR will fix the issues with `--queries-file` so that the workaround is not required. We will get that into 5.0.1.

**Comment by hjafarpour** [comment]
#1646 fixes this.
