### ISSUE TITLE
Failed to build master branch

### ISSUE THREAD

**Issue by ouertani** [confluentinc/ksql#3007]
The build of the master branch fails with the below stack:

```
[INFO] ksql-tools ......................................... SUCCESS [  5.461 s]
[INFO] ksql-version-metrics-client ........................ FAILURE [  0.963 s]
[INFO] ksql-rest-app ...................................... SKIPPED
[INFO] ksql-cli ........................................... SKIPPED
[INFO] ksql-examples ...................................... SKIPPED
[INFO] ksql-console-scripts ............................... SKIPPED
[INFO] ksql-etc ........................................... SKIPPED
[INFO] ksql-package ....................................... SKIPPED
[INFO] ksql-benchmark ..................................... SKIPPED
[INFO] ksql-functional-tests .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  56.064 s
[INFO] Finished at: 2019-06-23T22:00:21+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project ksql-version-metrics-client: Compilation failure: Compilation failure:
[ERROR] /Users/slim/dev/git/me/confluentinc/ksql/ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionChecker.java:[28,8] io.confluent.ksql.version.metrics.KsqlVersionChecker is not abstract and does not override abstract method zkClientProvider() in io.confluent.support.metrics.BaseMetricsReporter
[ERROR] /Users/slim/dev/git/me/confluentinc/ksql/ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionChecker.java:[40,5] no suitable constructor found for BaseMetricsReporter(java.lang.String,boolean,io.confluent.support.metrics.BaseSupportConfig,io.confluent.ksql.version.metrics.KsqlVersionCheckerResponseHandler,boolean)
[ERROR]     constructor io.confluent.support.metrics.BaseMetricsReporter.BaseMetricsReporter(java.lang.String,boolean,io.confluent.support.metrics.BaseSupportConfig) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR]     constructor io.confluent.support.metrics.BaseMetricsReporter.BaseMetricsReporter(java.lang.String,boolean,io.confluent.support.metrics.BaseSupportConfig,io.confluent.support.metrics.common.kafka.KafkaUtilities,io.confluent.support.metrics.submitters.ResponseHandler,boolean) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR] /Users/slim/dev/git/me/confluentinc/ksql/ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionChecker.java:[56,3] method does not override or implement a method from a supertype
[ERROR] /Users/slim/dev/git/me/confluentinc/ksql/ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionChecker.java:[61,3] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
```
This project has been deprecated https://github.com/confluentinc/support-metrics-common while the refered one is not accessible: https://github.com/confluentinc/ce-kafka

**Comment by spena** [comment]
I saw this issue today, but I could compile after pulling the latest changes of master. 
Could you try to update your repo?

**Comment by ouertani** [comment]
@spena still the same

**`mvn install -DskipTests -U`**

```
[INFO] /Users/slim/dev/git/me/confluentinc/ksql/ksql-version-metrics-client/target/generated-sources/avro/io/confluent/ksql/version/metrics/KsqlVersionMetrics.java: /Users/slim/dev/git/me/confluentinc/ksql/ksql-version-metrics-client/target/generated-sources/avro/io/confluent/ksql/version/metrics/KsqlVersionMetrics.java uses unchecked or unsafe operations.
[INFO] /Users/slim/dev/git/me/confluentinc/ksql/ksql-version-metrics-client/target/generated-sources/avro/io/confluent/ksql/version/metrics/KsqlVersionMetrics.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/slim/dev/git/me/confluentinc/ksql/ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionChecker.java:[28,8] io.confluent.ksql.version.metrics.KsqlVersionChecker is not abstract and does not override abstract method zkClientProvider() in io.confluent.support.metrics.BaseMetricsReporter
[ERROR] /Users/slim/dev/git/me/confluentinc/ksql/ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionChecker.java:[40,5] no suitable constructor found for BaseMetricsReporter(java.lang.String,boolean,io.confluent.support.metrics.BaseSupportConfig,io.confluent.ksql.version.metrics.KsqlVersionCheckerResponseHandler,boolean)
    constructor io.confluent.support.metrics.BaseMetricsReporter.BaseMetricsReporter(java.lang.String,boolean,io.confluent.support.metrics.BaseSupportConfig) is not applicable
      (actual and formal argument lists differ in length)
    constructor io.confluent.support.metrics.BaseMetricsReporter.BaseMetricsReporter(java.lang.String,boolean,io.confluent.support.metrics.BaseSupportConfig,io.confluent.support.metrics.common.kafka.KafkaUtilities,io.confluent.support.metrics.submitters.ResponseHandler,boolean) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /Users/slim/dev/git/me/confluentinc/ksql/ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionChecker.java:[56,3] method does not override or implement a method from a supertype
[ERROR] /Users/slim/dev/git/me/confluentinc/ksql/ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionChecker.java:[61,3] method does not override or implement a method from a supertype
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ksql-parent 5.4.0-SNAPSHOT:
[INFO]
[INFO] ksql-parent ........................................ SUCCESS [  5.189 s]
[INFO] ksql-test-util ..................................... SUCCESS [  7.072 s]
[INFO] ksql-udf ........................................... SUCCESS [  1.656 s]
[INFO] ksql-common ........................................ SUCCESS [ 22.710 s]
[INFO] KSQL UDF / UDAF :: Quickstart ...................... SUCCESS [  1.267 s]
[INFO] ksql-serde ......................................... SUCCESS [  5.292 s]
[INFO] ksql-metastore ..................................... SUCCESS [  3.381 s]
[INFO] ksql-parser ........................................ SUCCESS [  8.440 s]
[INFO] ksql-engine ........................................ SUCCESS [ 15.874 s]
[INFO] ksql-tools ......................................... SUCCESS [ 11.785 s]
[INFO] ksql-version-metrics-client ........................ FAILURE [  0.714 s]
[INFO] ksql-rest-app ...................................... SKIPPED
[INFO] ksql-cli ........................................... SKIPPED
[INFO] ksql-examples ...................................... SKIPPED
[INFO] ksql-console-scripts ............................... SKIPPED
[INFO] ksql-etc ........................................... SKIPPED
[INFO] ksql-package ....................................... SKIPPED
[INFO] ksql-benchmark ..................................... SKIPPED
[INFO] ksql-functional-tests .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by ouertani** [comment]
**`git log`**

```
commit 14d2bb76512a48d6d53ecac4f9500f13e39c4516 (HEAD -> master, upstream/master, origin/master, origin/HEAD, KSQL-2583)
Author: Almog Gavra <almog@confluent.io>
Date:   Mon Jun 24 11:21:23 2019 -0700

    feat: decimal math with other numbers (#3001)

commit 9a634b8a7ac8306d769f192790abbec9eaad2dd9
Merge: d85231316 d6619ee20
Author: Apurva Mehta <apurva@confluent.io>
Date:   Fri Jun 21 21:00:39 2019 -0700

    Merge branch '5.3.x'

```

**Comment by conker84** [comment]
Same problem here

**Comment by spena** [comment]
The build is fixed now.

**Comment by millin** [comment]
> The build is fixed now.

Not fixed

**Comment by ouertani** [comment]
@millin fixed, try to run this as docker file

```
FROM maven:3.6-jdk-8

# install git
CMD ["apt-get", "update"]
CMD ["apt-get", "upgrade"]
CMD ["apt-get", "install" , "git"]

RUN git clone https://github.com/confluentinc/ksql.git
WORKDIR ./ksql
CMD ["mvn", "clean","package", "-DskipTests"] 
```

**Comment by millin** [comment]
@ouertani Thanks, docker build successful.
But I still have the same error, when I tring build it locally from master:
```
$ mvn -v
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: ru_RU, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-20-generic", arch: "amd64", family: "unix"
```

**Comment by ouertani** [comment]
@millin I would recommend to 

`mv ~/.m2/repository/io/confluent ~/.m2/repository/io/confluent.bck`

and check again

**Comment by millin** [comment]
@ouertani It helps me! Thanks!
